#pragma once

#define POKEQUIZ_UI_BOTTOM_BUTTONS_BOTTOM_OFFSET 100
#define POKEQUIZ_UI_MAIN_FRAME_TOP_OFFSET 250
#define POKEQUIZ_UI_FRAME_MARGINS 10
#define POKEQUIZ_UI_FRAME_MARGIN_TOP 5
#define POKEQUIZ_UI_FRAME_BORDER_WIDTH 10
#define POKEQUIZ_UI_SMALL_FRAME_WIDTH 150 + 2 * POKEQUIZ_UI_FRAME_MARGINS